FROM openjdk:8 as build-stage
WORKDIR /app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN ./mvnw dependency:go-offline
COPY src src
RUN ./mvnw package -DskipTests
FROM openjdk:8-jre-alpine
COPY --from=build-stage /app/target/*.jar app.jar
EXPOSE 8443
ENTRYPOINT ["java","-jar","/app.jar"]
